# SPDX-License-Identifier: Apache-2.0

if(NOT DEFINED HUNDUN_SOURCE_ROOT OR
   NOT DEFINED HUNDUN_OUTER_BINARY_DIR OR
   NOT DEFINED HUNDUN_NESTED_BINARY_DIR OR
   NOT DEFINED HUNDUN_ARCHIVE_DIR OR
   NOT DEFINED HUNDUN_NESTED_CONFIG)
  message(FATAL_ERROR "Task22 tests-off setup inputs are incomplete")
endif()

load_cache(
  "${HUNDUN_OUTER_BINARY_DIR}"
  READ_WITH_PREFIX outer_
  CMAKE_GENERATOR
  CMAKE_GENERATOR_INSTANCE
  CMAKE_GENERATOR_PLATFORM
  CMAKE_GENERATOR_TOOLSET
  CMAKE_MAKE_PROGRAM
  CMAKE_BUILD_TYPE
  CMAKE_TOOLCHAIN_FILE
  CMAKE_SYSROOT
  CMAKE_C_COMPILER
  CMAKE_C_COMPILER_TARGET
  CMAKE_C_FLAGS
  CMAKE_C_FLAGS_DEBUG
  CMAKE_C_FLAGS_RELEASE
  CMAKE_C_FLAGS_RELWITHDEBINFO
  CMAKE_C_FLAGS_MINSIZEREL
  CMAKE_CXX_COMPILER
  CMAKE_CXX_COMPILER_TARGET
  CMAKE_CXX_FLAGS
  CMAKE_CXX_FLAGS_DEBUG
  CMAKE_CXX_FLAGS_RELEASE
  CMAKE_CXX_FLAGS_RELWITHDEBINFO
  CMAKE_CXX_FLAGS_MINSIZEREL
  CMAKE_EXE_LINKER_FLAGS
  CMAKE_EXE_LINKER_FLAGS_DEBUG
  CMAKE_EXE_LINKER_FLAGS_RELEASE
  CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO
  CMAKE_EXE_LINKER_FLAGS_MINSIZEREL
  CMAKE_MODULE_LINKER_FLAGS
  CMAKE_MODULE_LINKER_FLAGS_DEBUG
  CMAKE_MODULE_LINKER_FLAGS_RELEASE
  CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO
  CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL
  CMAKE_SHARED_LINKER_FLAGS
  CMAKE_SHARED_LINKER_FLAGS_DEBUG
  CMAKE_SHARED_LINKER_FLAGS_RELEASE
  CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO
  CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL
  CMAKE_STATIC_LINKER_FLAGS
  CMAKE_STATIC_LINKER_FLAGS_DEBUG
  CMAKE_STATIC_LINKER_FLAGS_RELEASE
  CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO
  CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL
  MPI_CXX_COMPILER
  MPI_CXX_COMPILER_FLAGS
  MPI_CXX_SKIP_MPICXX
  MPIEXEC_EXECUTABLE
  HUNDUN_ENABLE_ASAN
  HUNDUN_ENABLE_UBSAN)

if(NOT outer_CMAKE_GENERATOR)
  message(FATAL_ERROR "Task22 tests-off setup cannot recover the outer generator")
endif()

set(configure_command
    "${CMAKE_COMMAND}"
    -S "${HUNDUN_SOURCE_ROOT}"
    -B "${HUNDUN_NESTED_BINARY_DIR}"
    -G "${outer_CMAKE_GENERATOR}"
    "-DHUNDUN_BUILD_TESTS:BOOL=OFF"
    "-DCMAKE_ARCHIVE_OUTPUT_DIRECTORY:PATH=${HUNDUN_ARCHIVE_DIR}")

if(outer_CMAKE_GENERATOR_PLATFORM)
  list(APPEND configure_command -A "${outer_CMAKE_GENERATOR_PLATFORM}")
endif()
if(outer_CMAKE_GENERATOR_TOOLSET)
  list(APPEND configure_command -T "${outer_CMAKE_GENERATOR_TOOLSET}")
endif()

function(task22_forward_cache variable type)
  if(DEFINED outer_${variable} AND NOT "${outer_${variable}}" STREQUAL "")
    list(APPEND configure_command
         "-D${variable}:${type}=${outer_${variable}}")
    set(configure_command "${configure_command}" PARENT_SCOPE)
  endif()
endfunction()

foreach(variable IN ITEMS
    CMAKE_C_FLAGS
    CMAKE_C_FLAGS_DEBUG
    CMAKE_C_FLAGS_RELEASE
    CMAKE_C_FLAGS_RELWITHDEBINFO
    CMAKE_C_FLAGS_MINSIZEREL
    CMAKE_CXX_FLAGS
    CMAKE_CXX_FLAGS_DEBUG
    CMAKE_CXX_FLAGS_RELEASE
    CMAKE_CXX_FLAGS_RELWITHDEBINFO
    CMAKE_CXX_FLAGS_MINSIZEREL
    CMAKE_EXE_LINKER_FLAGS
    CMAKE_EXE_LINKER_FLAGS_DEBUG
    CMAKE_EXE_LINKER_FLAGS_RELEASE
    CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO
    CMAKE_EXE_LINKER_FLAGS_MINSIZEREL
    CMAKE_MODULE_LINKER_FLAGS
    CMAKE_MODULE_LINKER_FLAGS_DEBUG
    CMAKE_MODULE_LINKER_FLAGS_RELEASE
    CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO
    CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL
    CMAKE_SHARED_LINKER_FLAGS
    CMAKE_SHARED_LINKER_FLAGS_DEBUG
    CMAKE_SHARED_LINKER_FLAGS_RELEASE
    CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO
    CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL
    CMAKE_STATIC_LINKER_FLAGS
    CMAKE_STATIC_LINKER_FLAGS_DEBUG
    CMAKE_STATIC_LINKER_FLAGS_RELEASE
    CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO
    CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL
    MPI_CXX_COMPILER_FLAGS)
  task22_forward_cache("${variable}" STRING)
endforeach()

foreach(variable IN ITEMS
    CMAKE_C_COMPILER
    CMAKE_CXX_COMPILER
    CMAKE_MAKE_PROGRAM
    CMAKE_TOOLCHAIN_FILE
    MPI_CXX_COMPILER
    MPIEXEC_EXECUTABLE)
  task22_forward_cache("${variable}" FILEPATH)
endforeach()

foreach(variable IN ITEMS
    CMAKE_C_COMPILER_TARGET
    CMAKE_CXX_COMPILER_TARGET
    CMAKE_GENERATOR_INSTANCE
    CMAKE_SYSROOT)
  task22_forward_cache("${variable}" STRING)
endforeach()

foreach(variable IN ITEMS
    HUNDUN_ENABLE_ASAN
    HUNDUN_ENABLE_UBSAN
    MPI_CXX_SKIP_MPICXX)
  task22_forward_cache("${variable}" BOOL)
endforeach()

if(HUNDUN_NESTED_CONFIG)
  list(APPEND configure_command
       "-DCMAKE_BUILD_TYPE:STRING=${HUNDUN_NESTED_CONFIG}")
  string(TOUPPER "${HUNDUN_NESTED_CONFIG}" config_upper)
  list(APPEND configure_command
       "-DCMAKE_ARCHIVE_OUTPUT_DIRECTORY_${config_upper}:PATH=${HUNDUN_ARCHIVE_DIR}")
elseif(outer_CMAKE_BUILD_TYPE)
  list(APPEND configure_command
       "-DCMAKE_BUILD_TYPE:STRING=${outer_CMAKE_BUILD_TYPE}")
endif()

file(REMOVE_RECURSE "${HUNDUN_NESTED_BINARY_DIR}")
file(MAKE_DIRECTORY "${HUNDUN_ARCHIVE_DIR}")

execute_process(
  COMMAND ${configure_command}
  RESULT_VARIABLE configure_result
  OUTPUT_VARIABLE configure_output
  ERROR_VARIABLE configure_error)
if(NOT configure_result EQUAL 0)
  message(FATAL_ERROR
    "Task22 tests-off configure failed:\n${configure_output}${configure_error}")
endif()

set(build_command
    "${CMAKE_COMMAND}"
    --build "${HUNDUN_NESTED_BINARY_DIR}"
    --target hundun_flow hundun_linear hundun_material_diagnostics
    --parallel 2)
if(HUNDUN_NESTED_CONFIG)
  list(APPEND build_command --config "${HUNDUN_NESTED_CONFIG}")
endif()
execute_process(
  COMMAND ${build_command}
  RESULT_VARIABLE build_result
  OUTPUT_VARIABLE build_output
  ERROR_VARIABLE build_error)
if(NOT build_result EQUAL 0)
  message(FATAL_ERROR
    "Task22 tests-off build failed:\n${build_output}${build_error}")
endif()
