# SPDX-License-Identifier: Apache-2.0
cmake_minimum_required(VERSION 3.21)
file(STRINGS "${HUNDUN_STAGE3_CAPABILITY_LEDGER}" lines)
set(profile_count 0)
foreach(line IN LISTS lines)
  if(line MATCHES "^\\| profile-[1-9] ")
    math(EXPR profile_count "${profile_count} + 1")
  endif()
  if(line MATCHES "^\\|" AND NOT line MATCHES "^\\| (---|Capability)")
    string(REGEX MATCHALL "\\|" separators "${line}")
    list(LENGTH separators width)
    if(NOT width EQUAL 6 OR NOT line MATCHES "(implemented-and-accepted|deferred|out-of-scope)" OR NOT line MATCHES "\\| [^|]+ \\| [^|]+ \\| [^|]+ \\|$")
      message(FATAL_ERROR "invalid Stage 3 capability row: ${line}")
    endif()
  endif()
endforeach()
if(NOT profile_count EQUAL 9)
  message(FATAL_ERROR "Stage 3 capability ledger does not contain nine profiles")
endif()
file(READ "${HUNDUN_STAGE3_CAPABILITY_LEDGER}" ledger)
foreach(term IN ITEMS redistribution multigrid AMR GPU "moving immersed bodies" "rank-changing Restart" "96-cubed")
  string(FIND "${ledger}" "${term}" found)
  if(found LESS 0)
    message(FATAL_ERROR "Stage 3 limitation is missing: ${term}")
  endif()
endforeach()
