# SPDX-License-Identifier: Apache-2.0
# Developed by WANG YUDONG | Email: wangyudong@buaa.edu.cn | Github/Wechat: windcicada | Year.M: 2026.09
cmake_minimum_required(VERSION 3.21)

foreach(required IN ITEMS
    HUNDUN_GOVERNANCE_ROOT
    HUNDUN_PRODUCT_ROOT
    HUNDUN_BASE_MANIFEST
    HUNDUN_OUTPUT_MANIFEST)
  if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
    message(FATAL_ERROR "Stage 3 product projection requires ${required}")
  endif()
endforeach()

function(run_git root output)
  execute_process(
    COMMAND git -C "${root}" ${ARGN}
    RESULT_VARIABLE result
    OUTPUT_VARIABLE value
    ERROR_VARIABLE error
    OUTPUT_STRIP_TRAILING_WHITESPACE)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "git -C ${root} ${ARGN} failed:\n${value}${error}")
  endif()
  set(${output} "${value}" PARENT_SCOPE)
endfunction()

function(resolve_governance_path input output)
  if(IS_ABSOLUTE "${input}")
    set(resolved "${input}")
  else()
    set(resolved "${governance_root}/${input}")
  endif()
  cmake_path(NORMAL_PATH resolved OUTPUT_VARIABLE resolved)
  string(FIND "${resolved}" "${governance_root}/" prefix)
  if(NOT prefix EQUAL 0)
    message(FATAL_ERROR
      "projection manifest path escapes governance root: ${input}")
  endif()
  set(${output} "${resolved}" PARENT_SCOPE)
endfunction()

function(product_path_allowed path output)
  list(FIND base_paths "${path}" base_index)
  if(NOT base_index EQUAL -1)
    set(allowed TRUE)
  elseif("${path}" MATCHES
      "^(cmake|include/hundun|src|third_party|LICENSES|examples)/")
    set(allowed TRUE)
  elseif("${path}" MATCHES
      "^docs/(ai-skill|api|architecture|development|numerics|releases|user-guide|verification)/")
    set(allowed TRUE)
  else()
    set(allowed FALSE)
  endif()
  if("${path}" MATCHES
      "(^|/)(tests|[.]superpowers|[.]github|cases|design|handoff|plans|references|superpowers)(/|$)" OR
     "${path}" MATCHES "private|token" OR
     "${path}" STREQUAL "docs/development/source-policy.md")
    set(allowed FALSE)
  endif()
  set(${output} "${allowed}" PARENT_SCOPE)
endfunction()

foreach(root_variable IN ITEMS HUNDUN_GOVERNANCE_ROOT HUNDUN_PRODUCT_ROOT)
  set(root_value "${${root_variable}}")
  cmake_path(ABSOLUTE_PATH root_value NORMALIZE OUTPUT_VARIABLE root_value)
  if(NOT IS_DIRECTORY "${root_value}" OR IS_SYMLINK "${root_value}")
    message(FATAL_ERROR "${root_variable} is not a nonsymlink directory")
  endif()
  file(REAL_PATH "${root_value}" real_root)
  if(root_variable STREQUAL "HUNDUN_GOVERNANCE_ROOT")
    set(governance_root "${real_root}")
  else()
    set(product_root "${real_root}")
  endif()
endforeach()
if(governance_root STREQUAL product_root)
  message(FATAL_ERROR "governance and product roots must differ")
endif()

resolve_governance_path("${HUNDUN_BASE_MANIFEST}" base_manifest)
resolve_governance_path("${HUNDUN_OUTPUT_MANIFEST}" output_manifest)
if(base_manifest STREQUAL output_manifest)
  message(FATAL_ERROR "base and output projection manifests must differ")
endif()
if(NOT EXISTS "${base_manifest}" OR IS_SYMLINK "${base_manifest}")
  message(FATAL_ERROR "product-projection-manifest is missing or is a symlink")
endif()

foreach(root IN ITEMS "${governance_root}" "${product_root}")
  run_git("${root}" observed_root rev-parse --show-toplevel)
  file(REAL_PATH "${observed_root}" observed_root)
  if(NOT observed_root STREQUAL root)
    message(FATAL_ERROR "projection root is not a Git worktree root: ${root}")
  endif()
  run_git("${root}" status status --porcelain=v1 --untracked-files=normal)
  if(NOT status STREQUAL "")
    message(FATAL_ERROR "projection root is not clean: ${root}")
  endif()
endforeach()
run_git("${product_root}" product_remotes remote)
if(NOT product_remotes STREQUAL "")
  message(FATAL_ERROR "product projection requires zero remotes")
endif()

file(STRINGS "${base_manifest}" manifest_lines)
list(LENGTH manifest_lines manifest_height)
if(manifest_height LESS 2)
  message(FATAL_ERROR "product projection base manifest is empty")
endif()
list(GET manifest_lines 0 manifest_header)
if(NOT manifest_header STREQUAL
    "path\tproduct_blob\tgovernance_blob\trelation")
  message(FATAL_ERROR "product projection base manifest header mismatch")
endif()

set(base_paths)
set(base_product_blobs)
set(base_relations)
list(REMOVE_AT manifest_lines 0)
foreach(line IN LISTS manifest_lines)
  if(line STREQUAL "")
    continue()
  endif()
  string(REPLACE "\t" ";" columns "${line}")
  list(LENGTH columns width)
  if(NOT width EQUAL 4)
    message(FATAL_ERROR "invalid product projection manifest row: ${line}")
  endif()
  list(GET columns 0 path)
  list(GET columns 1 product_blob)
  list(GET columns 2 governance_blob)
  list(GET columns 3 relation)
  if(path STREQUAL "" OR IS_ABSOLUTE "${path}" OR
     "${path}" MATCHES "(^|/)[.][.](/|$)|\\\\" OR
     "${path}" MATCHES
       "(^|/)(tests|[.]superpowers|[.]github|cases|design|handoff|plans|references|superpowers)(/|$)" OR
     "${path}" MATCHES "private|token")
    message(FATAL_ERROR "illegal product projection path: ${path}")
  endif()
  string(LENGTH "${product_blob}" product_blob_length)
  string(LENGTH "${governance_blob}" governance_blob_length)
  if(NOT product_blob_length EQUAL 40 OR
     NOT governance_blob_length EQUAL 40 OR
     NOT product_blob MATCHES "^[0-9a-f]+$" OR
     NOT governance_blob MATCHES "^[0-9a-f]+$")
    message(FATAL_ERROR "invalid blob identity for product path: ${path}")
  endif()
  if(NOT relation MATCHES
      "^(identical|product_tests_off_preset|product_only_override)$")
    message(FATAL_ERROR "invalid product relation for path: ${path}")
  endif()
  if(relation STREQUAL "product_tests_off_preset" AND
     NOT path STREQUAL "CMakePresets.json")
    message(FATAL_ERROR "tests-off relation is bound to CMakePresets.json")
  endif()
  if(relation STREQUAL "product_only_override" AND
     NOT path STREQUAL "VERSION")
    message(FATAL_ERROR "product-only relation is bound to VERSION")
  endif()
  list(FIND base_paths "${path}" duplicate_index)
  if(NOT duplicate_index EQUAL -1)
    message(FATAL_ERROR "duplicate product projection path: ${path}")
  endif()
  list(APPEND base_paths "${path}")
  list(APPEND base_product_blobs "${product_blob}")
  list(APPEND base_relations "${relation}")
endforeach()

# Authenticate the complete current product baseline before making any change.
run_git("${product_root}" product_tracked ls-files)
string(REPLACE "\n" ";" product_tracked "${product_tracked}")
foreach(path IN LISTS product_tracked)
  if(path STREQUAL "")
    continue()
  endif()
  list(FIND base_paths "${path}" base_index)
  if(base_index EQUAL -1)
    message(FATAL_ERROR "unexpected tracked product path: ${path}")
  endif()
endforeach()
list(LENGTH base_paths base_count)
if(base_count GREATER 0)
  math(EXPR last_base "${base_count} - 1")
  foreach(index RANGE 0 ${last_base})
    list(GET base_paths ${index} path)
    list(GET base_product_blobs ${index} expected_blob)
    if(NOT EXISTS "${product_root}/${path}" OR
       IS_SYMLINK "${product_root}/${path}")
      message(FATAL_ERROR "product baseline path is missing or symlinked: ${path}")
    endif()
    run_git("${product_root}" observed_blob rev-parse "HEAD:${path}")
    if(NOT observed_blob STREQUAL expected_blob)
      message(FATAL_ERROR "product baseline blob mismatch: ${path}")
    endif()
  endforeach()
endif()

# Derive the target set from the authenticated base plus explicit public/product
# roots in the accepted governance candidate.  Everything is validated before
# the first product write.
run_git("${governance_root}" governance_tracked ls-files)
string(REPLACE "\n" ";" governance_tracked "${governance_tracked}")
set(target_paths)
set(target_governance_blobs)
foreach(path IN LISTS governance_tracked)
  if(path STREQUAL "")
    continue()
  endif()
  product_path_allowed("${path}" allowed)
  if(NOT allowed)
    continue()
  endif()
  if(NOT EXISTS "${governance_root}/${path}" OR
     IS_SYMLINK "${governance_root}/${path}")
    message(FATAL_ERROR "governance product path is missing or symlinked: ${path}")
  endif()
  run_git("${governance_root}" governance_blob rev-parse "HEAD:${path}")
  list(APPEND target_paths "${path}")
  list(APPEND target_governance_blobs "${governance_blob}")
endforeach()
foreach(path IN LISTS base_paths)
  list(FIND target_paths "${path}" target_index)
  if(target_index EQUAL -1)
    message(FATAL_ERROR
      "refusing to delete authenticated product path absent from governance: ${path}")
  endif()
endforeach()

set(final_rows)
list(LENGTH target_paths target_count)
if(target_count GREATER 0)
  math(EXPR last_target "${target_count} - 1")
  foreach(index RANGE 0 ${last_target})
    list(GET target_paths ${index} path)
    list(GET target_governance_blobs ${index} governance_blob)
    list(FIND base_paths "${path}" base_index)
    if(path STREQUAL "CMakePresets.json")
      set(relation product_tests_off_preset)
    elseif(path STREQUAL "VERSION")
      set(relation product_only_override)
    else()
      set(relation identical)
    endif()

    if(relation STREQUAL "product_tests_off_preset")
      # The authenticated product preset is intentionally preserved.
    elseif(relation STREQUAL "product_only_override")
      file(WRITE "${product_root}/${path}" "0.2.0\n")
    else()
      cmake_path(GET path PARENT_PATH parent)
      if(NOT parent STREQUAL "")
        file(MAKE_DIRECTORY "${product_root}/${parent}")
      endif()
      file(COPY_FILE "${governance_root}/${path}" "${product_root}/${path}"
           ONLY_IF_DIFFERENT)
    endif()
    run_git("${product_root}" product_blob hash-object -- "${path}")
    list(APPEND final_rows
      "${path}\t${product_blob}\t${governance_blob}\t${relation}")
  endforeach()
endif()

cmake_path(GET output_manifest PARENT_PATH output_parent)
file(MAKE_DIRECTORY "${output_parent}")
set(final_manifest "path\tproduct_blob\tgovernance_blob\trelation\n")
foreach(row IN LISTS final_rows)
  string(APPEND final_manifest "${row}\n")
endforeach()
file(WRITE "${output_manifest}" "${final_manifest}")
message(STATUS
  "Stage 3 product projection wrote ${target_count} manifest-bound paths")
