# SPDX-License-Identifier: Apache-2.0
# Developed by WANG YUDONG | Email: wangyudong@buaa.edu.cn | Github/Wechat: windcicada | Year.M: 2026.09
cmake_minimum_required(VERSION 3.21)
foreach(path IN ITEMS "${HUNDUN_STAGE3_ACCEPTANCE_SCRIPT}" "${HUNDUN_STAGE3_ACCEPTANCE_INVENTORY}")
  if(NOT EXISTS "${path}")
    message(FATAL_ERROR "Stage 3 acceptance authority is missing: ${path}")
  endif()
endforeach()
execute_process(COMMAND bash -n "${HUNDUN_STAGE3_ACCEPTANCE_SCRIPT}" RESULT_VARIABLE syntax)
if(NOT syntax EQUAL 0)
  message(FATAL_ERROR "Stage 3 acceptance launcher syntax is invalid")
endif()
file(READ "${HUNDUN_STAGE3_ACCEPTANCE_SCRIPT}" launcher)
foreach(token IN ITEMS "--list" "--group" "--candidate-head" "--debug-root" "--release-root" "--asan-root" "--ubsan-root" "--tests-off-root" "low-cost" "scientific" "performance" "sanitizer" "governance")
  string(FIND "${launcher}" "${token}" found)
  if(found LESS 0)
    message(FATAL_ERROR "Stage 3 launcher mode is missing: ${token}")
  endif()
endforeach()
string(FIND "${launcher}" "</dev/null" stdin_isolation)
if(stdin_isolation LESS 0)
  message(FATAL_ERROR "Stage 3 launcher does not isolate row commands from inventory stdin")
endif()
string(FIND "${launcher}" "ASAN_OPTIONS=detect_leaks=0" asan_environment)
if(asan_environment LESS 0)
  message(FATAL_ERROR "Stage 3 launcher does not isolate ASan from external MPI leak reports")
endif()
file(STRINGS "${HUNDUN_STAGE3_ACCEPTANCE_INVENTORY}" rows)
list(POP_FRONT rows header)
if(NOT header STREQUAL "row_id\tgroup\trequired\tresource_class\tranks\tbuild_role\tproducer_target\texecutable\targv\ttimeout_s\tartifact_subdir")
  message(FATAL_ERROR "Stage 3 acceptance inventory header differs")
endif()
set(ids "")
foreach(row IN LISTS rows)
  string(REPLACE "\t" ";" columns "${row}")
  list(LENGTH columns count)
  if(NOT count EQUAL 11)
    message(FATAL_ERROR "Stage 3 inventory row width differs: ${row}")
  endif()
  list(GET columns 0 id)
  list(GET columns 1 group)
  list(GET columns 2 required)
  list(GET columns 5 role)
  list(GET columns 6 producer)
  list(GET columns 8 argv)
  list(FIND ids "${id}" duplicate)
  if(NOT duplicate EQUAL -1 OR id STREQUAL "" OR (required STREQUAL "1" AND producer STREQUAL ""))
    message(FATAL_ERROR "Stage 3 inventory row identity differs: ${id}")
  endif()
  list(APPEND ids "${id}")
  if((group STREQUAL "scientific" OR group STREQUAL "performance") AND NOT role STREQUAL "release")
    message(FATAL_ERROR "formal Stage 3 row is not Release: ${id}")
  endif()
  if(id STREQUAL "restart-fast-r4")
    if(NOT producer STREQUAL "test_immersed_transaction"
       OR NOT argv STREQUAL "test_checkpoint_v3_4_rank")
      message(FATAL_ERROR "Stage 3 restart-fast-r4 producer binding differs")
    endif()
  elseif(id MATCHES "^checkpoint-continuation-n12-r[124]$")
    if(NOT producer STREQUAL "test_checkpoint_v3_density_profiles"
       OR NOT argv STREQUAL "${id}")
      message(FATAL_ERROR "Stage 3 formal continuation binding differs: ${id}")
    endif()
  endif()
endforeach()
set(required_ids wale-tgv-convergence-r1 wale-tgv-n24-r2 wale-tgv-n24-r4 wale-channel-n48-r1 constant-ibm-wale-n48-r1 constant-ibm-wale-n24-r1 constant-ibm-wale-n24-r2 constant-ibm-wale-n24-r4 checkpoint-continuation-n12-r1 checkpoint-continuation-n12-r2 checkpoint-continuation-n12-r4 stage3-exact-counters-n24-r1 stage3-exact-counters-n24-r2 stage3-exact-counters-n24-r4 asan-immersed-wale-constant-fast asan-material-wale-composition-fast asan-ideal-wale-composition-fast asan-checkpoint-density-profiles-fast asan-evidence-manifest-unit ubsan-immersed-wale-constant-fast ubsan-material-wale-composition-fast ubsan-ideal-wale-composition-fast ubsan-checkpoint-density-profiles-fast ubsan-evidence-manifest-unit)
foreach(id IN LISTS required_ids)
  list(FIND ids "${id}" found)
  if(found EQUAL -1)
    message(FATAL_ERROR "required Stage 3 row is missing: ${id}")
  endif()
endforeach()
