# SPDX-License-Identifier: Apache-2.0
# Developed by WANG YUDONG | Email: wangyudong@buaa.edu.cn | Github/Wechat: windcicada | Year.M: 2026.09

# Release-gate correctness manifest.  Keep this list explicit: adding a test
# requires a candidate-identity change and cannot silently broaden a frozen
# selector.  Small-grid timings are intentionally absent; core_hot_resource is
# a lifecycle/allocation contract, not a performance acceptance test.
set(HUNDUN_V04_FOCUSED_TESTS
  v04_evidence_workflow
  v04_app_cli_continuity_witness
  v04_app_case_allocation_mpi_1
  v04_app_case_allocation_mpi_2
  v04_app_output_failure_mpi_1
  v04_app_output_failure_mpi_2
  v04_app_output_failure_mpi_4
  v04_product_adaptive_limits_mpi_1
  v04_product_adaptive_limits_mpi_2
  v04_product_adaptive_limits_mpi_4
  v04_evidence_performance_policy
  v04_literature_workflow
  v04_literature_partial_receipt
  v04_public_headers
  v04_solver_low_mach_mms
  v04_solver_enthalpy_terms
  v04_solver_source_stage
  v04_solver_species_conservation
  v04_solver_pressure_storage
  v04_solver_thermophysical_coupling
  v04_solver_pressure_energy_schur
  v04_solver_pressure_energy_globalization
  v04_solver_pressure_energy_globalization_mpi_1
  v04_solver_pressure_energy_globalization_mpi_2
  v04_solver_pressure_energy_globalization_mpi_4
  v04_solver_piso_authority
  v04_solver_piso_mutation
  v04_solver_piso_checkerboard
  v04_solver_piso_temporal_order
  v04_solver_initialization_projection
  v04_solver_initialization_projection_mpi_1
  v04_solver_initialization_projection_mpi_2
  v04_solver_initialization_projection_mpi_4
  v04_solver_ibm_pressure_operator
  v04_solver_ibm_equation_interface
  v04_solver_ibm_force_oracle
  v04_solver_ibm_force_mutation
  v04_solver_equations_mpi_1
  v04_solver_equations_mpi_2
  v04_solver_equations_mpi_4
  v04_solver_piso_mpi_1
  v04_solver_piso_mpi_2
  v04_solver_piso_mpi_4
  v04_solver_ibm_physical_boundary_flux_mpi_1
  v04_solver_ibm_physical_boundary_flux_mpi_2
  v04_solver_ibm_physical_boundary_flux_mpi_4
  v04_solver_ibm_force_mpi_1
  v04_solver_ibm_force_mpi_2
  v04_solver_ibm_force_mpi_4
  v04_mesh_ibm_quadratic
  v04_mesh_ibm_surface
  v04_mesh_ibm_order
  v04_mesh_ibm_stencil_mpi_1
  v04_mesh_ibm_stencil_mpi_2
  v04_mesh_ibm_stencil_mpi_4
  v04_mesh_ibm_plan_1
  v04_mesh_ibm_plan_2
  v04_mesh_ibm_plan_4
  v04_core_execution_graph
  v04_core_product_freeze
  v04_core_hot_resource
  v04_core_product_freeze_mpi_1
  v04_core_product_freeze_mpi_2
  v04_core_product_freeze_mpi_4
  v04_core_product_localized_immersed_compile_mpi_2
  v04_core_product_localized_immersed_compile_mpi_4
  v04_core_product_localized_immersed_bind_fail_close_mpi_2
  v04_core_product_localized_immersed_bind_fail_close_mpi_4
  v04_core_candidate_globalization_red_mpi_1
  v04_core_candidate_globalization_red_mpi_2
  v04_core_candidate_globalization_red_mpi_4
  v04_core_multispecies_open_mpi_1
  v04_core_multispecies_open_mpi_2
  v04_core_multispecies_open_mpi_4
  v04_core_fresh_open_eos_flux_mpi_1
  v04_core_fresh_open_eos_flux_mpi_2
  v04_core_fresh_open_eos_flux_mpi_4
  v04_core_fresh_initialize_contract_mpi_1
  v04_core_fresh_initialize_contract_mpi_2
  v04_core_fresh_initialize_contract_mpi_4
  v04_core_restart_allocation_contract_mpi_1
  v04_core_restart_allocation_contract_mpi_2
  v04_core_restart_allocation_contract_mpi_4
  v04_product_pressure_energy_retry_mpi_1
  v04_product_pressure_energy_retry_mpi_2
  v04_product_pressure_energy_retry_mpi_4
  v04_product_pressure_energy_temporal_convergence
  v04_product_fresh_projection
  v04_product_fresh_projection_mpi_1
  v04_product_fresh_projection_mpi_2
  v04_product_fresh_projection_mpi_4
  v04_core_resource_contract
  v04_core_transaction
  v04_core_transaction_mpi_1
  v04_core_transaction_mpi_2
  v04_core_transaction_mpi_4
  v04_io_restart_mpi_4
  v04_io_product_path
  v04_restart_rank_change_continue
  v04_app_init_case
  v04_app_driver
  v04_solver_linear_lifecycle
  v04_solver_mg_reuse
  v04_solver_mg_chebyshev
  v04_solver_mg_convergence
  v04_solver_mg_coarse_use
  v04_solver_mg_line_relaxation
  v04_solver_mg_krylov_isolation
  v04_solver_hypre_isolation
  v04_solver_hypre_communicator_mpi_2
  v04_solver_hypre_communicator_mpi_4
  v04_solver_mg_mpi_1
  v04_solver_mg_mpi_2
  v04_solver_mg_mpi_4
  v04_solver_mg_update_contract_mpi_2
  v04_solver_mg_update_contract_mpi_4
  v04_solver_mg_odd_partition_mpi_2
  v04_solver_mg_odd_partition_mpi_4
  v04_solver_krylov_mpi_1
  v04_solver_krylov_mpi_2
  v04_solver_krylov_mpi_4
  v04_solver_reduction_mpi_1
  v04_solver_reduction_mpi_2
  v04_solver_reduction_mpi_4
  v04_physics_thermo
  v04_physics_thermophysical_compiler_1
  v04_physics_thermophysical_compiler_2
  v04_physics_thermophysical_compiler_4
  v04_physics_transport
  v04_physics_contribution
  v04_physics_wale
  v04_physics_vreman
  v04_physics_wall_function
  v04_physics_turbulence_mpi_1
  v04_physics_turbulence_mpi_2
  v04_physics_turbulence_mpi_4
  v04_physics_closed_mass_1
  v04_physics_closed_mass_2
  v04_physics_closed_mass_4
  v04_bc_compile
  v04_bc_apply
  v04_bc_nscbc
  v04_bc_time_1
  v04_bc_time_2
  v04_bc_time_4
  v04_bc_decomposition_mpi_1
  v04_bc_decomposition_mpi_2
  v04_bc_decomposition_mpi_4
  v04_parallel_cpu_1
  v04_parallel_cpu_2
  v04_parallel_cpu_4
  v04_parallel_halo_mpi_1
  v04_parallel_halo_mpi_2
  v04_parallel_halo_mpi_4
  v04_parallel_halo_failure_1
  v04_parallel_halo_failure_2
  v04_parallel_halo_failure_4
)

# Keep one direct/serial route plus MPI-2 for each new coupled path.  Paths
# registered only through mpiexec use MPI-1 as the direct analogue; MPI-4 stays
# in the complete focused gate without multiplying sanitizer runtime.
set(HUNDUN_V04_FOCUSED_SANITIZER_TESTS
  v04_app_case_allocation_mpi_1
  v04_app_case_allocation_mpi_2
  v04_app_output_failure_mpi_1
  v04_app_output_failure_mpi_2
  v04_product_adaptive_limits_mpi_1
  v04_product_adaptive_limits_mpi_2
  v04_public_headers
  v04_solver_low_mach_mms
  v04_solver_enthalpy_terms
  v04_solver_species_conservation
  v04_solver_pressure_energy_schur
  v04_solver_pressure_energy_globalization
  v04_solver_pressure_energy_globalization_mpi_2
  v04_solver_initialization_projection
  v04_solver_initialization_projection_mpi_2
  v04_solver_piso_mutation
  v04_solver_equations_mpi_1
  v04_solver_equations_mpi_2
  v04_solver_mg_chebyshev
  v04_solver_mg_convergence
  v04_solver_mg_line_relaxation
  v04_solver_ibm_equation_interface
  v04_solver_ibm_force_mutation
  v04_mesh_ibm_stencil_mpi_1
  v04_mesh_ibm_stencil_mpi_2
  v04_mesh_ibm_plan_1
  v04_mesh_ibm_plan_2
  v04_app_driver
  v04_core_product_freeze
  v04_core_product_localized_immersed_compile_mpi_2
  v04_core_product_localized_immersed_bind_fail_close_mpi_2
  v04_core_candidate_globalization_red_mpi_1
  v04_core_candidate_globalization_red_mpi_2
  v04_core_multispecies_open_mpi_1
  v04_core_multispecies_open_mpi_2
  v04_core_fresh_open_eos_flux_mpi_1
  v04_core_fresh_open_eos_flux_mpi_2
  v04_core_fresh_initialize_contract_mpi_1
  v04_core_fresh_initialize_contract_mpi_2
  v04_core_restart_allocation_contract_mpi_1
  v04_core_restart_allocation_contract_mpi_2
  v04_product_pressure_energy_retry_mpi_1
  v04_product_pressure_energy_retry_mpi_2
  v04_product_pressure_energy_temporal_convergence
  v04_product_fresh_projection
  v04_product_fresh_projection_mpi_2
  v04_core_transaction
)
