# SPDX-License-Identifier: Apache-2.0
# Developed by WANG YUDONG | Email: wangyudong@buaa.edu.cn | Github/Wechat: windcicada | Year.M: 2026.09

function(hundun_source_status_metadata status_result status
         output_clean output_summary)
  if(NOT "${status_result}" STREQUAL "0")
    set(clean "false")
    set(summary "unavailable")
  elseif("${status}" STREQUAL "")
    set(clean "true")
    set(summary "")
  else()
    string(SHA256 digest "${status}")
    set(clean "false")
    set(summary "git-status-sha256:${digest}")
  endif()
  set("${output_clean}" "${clean}" PARENT_SCOPE)
  set("${output_summary}" "${summary}" PARENT_SCOPE)
endfunction()

function(hundun_escape_cpp_string input output)
  set(escaped "${input}")
  string(REPLACE "\\" "\\\\" escaped "${escaped}")
  string(REPLACE "\"" "\\\"" escaped "${escaped}")
  string(REPLACE "\n" "\\n" escaped "${escaped}")
  string(REPLACE "\r" "\\r" escaped "${escaped}")
  string(REPLACE "\t" "\\t" escaped "${escaped}")
  set("${output}" "${escaped}" PARENT_SCOPE)
endfunction()

# git archive expands this provenance record through export-subst. Exported
# sources retain the original Git identity and a separately computed content
# digest; the archive marker alone makes no claim about a pristine worktree.
function(hundun_archive_source_metadata root commit_output tree_output available_output)
  set(commit "unavailable")
  set(tree "unavailable")
  set(available FALSE)
  if(EXISTS "${root}/.git_archival.txt")
    file(READ "${root}/.git_archival.txt" text LIMIT 512)
    string(REPLACE "\r\n" "\n" text "${text}")
    if(text MATCHES "^HUNDUN_SOURCE_ARCHIVE_V1\ncommit=([0-9a-fA-F]+)\ntree=([0-9a-fA-F]+)\n$")
      set(candidate_commit "${CMAKE_MATCH_1}")
      set(candidate_tree "${CMAKE_MATCH_2}")
      string(LENGTH "${candidate_commit}" commit_length)
      string(LENGTH "${candidate_tree}" tree_length)
      if(commit_length EQUAL 40 AND tree_length EQUAL 40)
        string(TOLOWER "${candidate_commit}" commit)
        string(TOLOWER "${candidate_tree}" tree)
        set(available TRUE)
      endif()
    endif()
  endif()
  set(${commit_output} "${commit}" PARENT_SCOPE)
  set(${tree_output} "${tree}" PARENT_SCOPE)
  set(${available_output} "${available}" PARENT_SCOPE)
endfunction()
